.EEEEEE
======================================================================
ERROR: test_list_int (__main__.Test02_ModifyContact)
*** Test02 *** Calling the 'modify_contact' method passing a positional argument equal to [['Richard','Stallman'],['Bill','Gates']], a keyword argument first_name equal to 'Steve', a keyword argument last_name equal to 'Jobs', and a keyword argument index equal to '1' should result in a contact list [['Richard','Stallman'],['Steve','Jobs']] ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/brian/Documents/cpsc223p/lab3/test.py", line 24, in test_list_int
    modify_contact(contacts, index = 1, first_name = "Steve", last_name = "Jobs")
TypeError: modify_contact() got an unexpected keyword argument 'index'

======================================================================
ERROR: test_list_int (__main__.Test03_ModifyContact)
*** Test03 *** Calling the 'modify_contact' method passing a positional argument equal to [['Richard','Stallman'], a keyword argument first_name equal to 'Steve', a keyword argument last_name equal to 'Jobs', and a keyword argument index equal to '5' should result in a contact list [['Richard','Stallman']] and a return value of False ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/brian/Documents/cpsc223p/lab3/test.py", line 34, in test_list_int
    x = modify_contact(contacts, index = 5, first_name = "Steve", last_name = "Jobs")
TypeError: modify_contact() got an unexpected keyword argument 'index'

======================================================================
ERROR: test_list_int (__main__.Test04_DeleteContact)
*** Test04 *** Calling the 'delete_contact' method passing a positional argument equal to [['Richard','Stallman'],['Bill','Gates'],['Steve','Jobs']], and a keyword argument index equal to '1' should result in a contact list [['Richard','Stallman'],['Steve','Jobs']] ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/brian/Documents/cpsc223p/lab3/test.py", line 45, in test_list_int
    delete_contact(contacts, index = 1)
TypeError: delete_contact() got an unexpected keyword argument 'index'

======================================================================
ERROR: test_list_int (__main__.Test05_DeleteContact)
*** Test05 *** Calling the 'delete_contact' method passing a positional argument equal to [['Richard','Stallman'],['Steve','Jobs']], and a keyword argument index equal to '5' should result in a contact list [['Richard','Stallman'],['Steve','Jobs']] and a return value of False ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/brian/Documents/cpsc223p/lab3/test.py", line 55, in test_list_int
    x = delete_contact(contacts, index = 5)
TypeError: delete_contact() got an unexpected keyword argument 'index'

======================================================================
ERROR: test_list_int (__main__.Test06_SortContacts)
*** Test06 *** Calling the 'sort_contacts' method passing a positional argument equal to [['Richard','Stallman'],['Bill','Gates'],['Steve','Jobs']], and a keyword argument column equal to '0' should result in a contact list [['Bill','Gates'], ['Richard', 'Stallman'], ['Steve', 'Jobs']] ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/brian/Documents/cpsc223p/lab3/test.py", line 66, in test_list_int
    sort_contacts(contacts, column = 0)
NameError: name 'sort_contacts' is not defined

======================================================================
ERROR: test_list_int (__main__.Test07_SortContacts)
*** Test07 *** Calling the 'sort_contacts' method passing a positional argument equal to [['Richard','Stallman'],['Bill','Gates'],['Steve','Jobs']], and a keyword argument column equal to '1' should result in a contact list [['Bill', 'Gates'], ['Steve', 'Jobs'], ['Richard', 'Stallman']] ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/brian/Documents/cpsc223p/lab3/test.py", line 76, in test_list_int
    sort_contacts(contacts, column = 1)
NameError: name 'sort_contacts' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.006s

FAILED (errors=6)
